"""
Django settings for thaqaf_arabi project.

Generated by 'django-admin startproject' using Django 5.1.5.
"""

import os
from pathlib import Path

# ==============================
# المسارات الأساسية
# ==============================
BASE_DIR = Path(__file__).resolve().parent.parent

# ==============================
# الإعدادات العامة
# ==============================
SECRET_KEY = 'django-insecure-(pb#7pof3f!*qwlhw(ls4v-i1t$ks(l-4e-_l$jv*)oa6z)kuo'

DEBUG = False

ALLOWED_HOSTS = ["*"]


# ==============================
# التطبيقات
# ==============================
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'main',  # ← تطبيقك الأساسي
    'ckeditor',
    'ckeditor_uploader',
        'django.contrib.sitemaps',
]


# ==============================
# Middleware
# ==============================
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]


# ==============================
# ملفات العناوين
# ==============================
ROOT_URLCONF = 'thaqaf_arabi.urls'


# ==============================
# القوالب (Templates)
# ==============================
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        # إذا عندك مجلد templates عام ضيفه هنا
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]


WSGI_APPLICATION = 'thaqaf_arabi.wsgi.application'


# ==============================
# قاعدة البيانات
# ==============================
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# ==============================
# التحقق من كلمات المرور
# ==============================
AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator'},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
]


# ==============================
# اللغة والمنطقة الزمنية
# ==============================
LANGUAGE_CODE = 'ar'        # ← عربي
TIME_ZONE = 'Asia/Riyadh'   # ← توقيت السعودية واليمن
USE_I18N = True
USE_TZ = True


# ==============================
# الملفات الثابتة Static
# ==============================
STATIC_URL = '/static/'
STATICFILES_DIRS = [os.path.join(BASE_DIR, 'main/static')]
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')


# ==============================
# الإعداد الافتراضي للمفتاح الأساسي
# ==============================
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

CKEDITOR_UPLOAD_PATH = "uploads/"
# إعدادات البريد الإلكتروني
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = 'halax.7y7@gmail.com'
EMAIL_HOST_PASSWORD = 'bfrb vchm zxys ivmi'
DEFAULT_FROM_EMAIL = EMAIL_HOST_USER
