# Generated by Django 5.1.5 on 2025-11-03 20:41

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_article_image_url_category_image_category_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='محتوى المقال'),
        ),
    ]
