# Generated by Django 5.1.5 on 2025-11-03 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_article_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='الثَّقَف العربي', max_length=200, verbose_name='اسم الموقع')),
                ('hero_background', models.ImageField(blank=True, null=True, upload_to='site/', verbose_name='صورة الخلفية (Hero)')),
                ('hero_text', models.CharField(blank=True, max_length=250, null=True, verbose_name='نص المقدمة')),
                ('hero_subtext', models.CharField(blank=True, max_length=250, null=True, verbose_name='نص فرعي للمقدمة')),
            ],
            options={
                'verbose_name': 'إعدادات الموقع',
                'verbose_name_plural': 'إعدادات الموقع',
            },
        ),
    ]
