# Generated by Django 5.1.5 on 2025-11-03 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_sitesettings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitesettings',
            name='hero_subtext',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='hero_text',
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='footer_text',
            field=models.TextField(blank=True, null=True, verbose_name='نص الفوتر'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='hero_background_url',
            field=models.URLField(blank=True, null=True, verbose_name='رابط خلفية الهيرو (URL)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='hero_subtitle',
            field=models.TextField(blank=True, null=True, verbose_name='وصف الهيرو'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='hero_title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='عنوان الهيرو (Hero)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='site_logo/', verbose_name='شعار الموقع'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='hero_background',
            field=models.ImageField(blank=True, null=True, upload_to='hero_backgrounds/', verbose_name='خلفية الهيرو'),
        ),
    ]
