# Generated by Django 5.1.5 on 2025-11-05 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_sitesettings_hero_subtext_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='العنوان')),
                ('description', models.TextField(blank=True, verbose_name='الوصف')),
                ('media_type', models.CharField(choices=[('image', 'صورة'), ('video', 'فيديو'), ('news', 'خبر مصور')], max_length=10, verbose_name='النوع')),
                ('image', models.ImageField(blank=True, null=True, upload_to='gallery_images/', verbose_name='الصورة')),
                ('video_url', models.URLField(blank=True, null=True, verbose_name='رابط الفيديو (YouTube أو غيره)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'عنصر معرض',
                'verbose_name_plural': 'المعرض',
            },
        ),
        migrations.CreateModel(
            name='MediaItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='العنوان')),
                ('type', models.CharField(choices=[('image', 'صورة'), ('video', 'فيديو'), ('news', 'خبر')], max_length=10, verbose_name='النوع')),
                ('description', models.TextField(blank=True, null=True, verbose_name='الوصف')),
                ('image', models.ImageField(blank=True, null=True, upload_to='gallery/', verbose_name='صورة')),
                ('image_url', models.URLField(blank=True, null=True, verbose_name='رابط الصورة (URL)')),
                ('video_url', models.URLField(blank=True, null=True, verbose_name='رابط الفيديو (YouTube أو خارجي)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'عنصر وسائط',
                'verbose_name_plural': '📷 معرض الصور والفيديوهات',
            },
        ),
    ]
