# Generated by Django 5.1.5 on 2025-11-05 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_galleryitem_mediaitem'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GalleryItem',
        ),
        migrations.RenameField(
            model_name='mediaitem',
            old_name='type',
            new_name='media_type',
        ),
    ]
