# Generated by Django 5.1.5 on 2025-11-05 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_delete_galleryitem_rename_type_mediaitem_media_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان العنصر')),
                ('description', models.TextField(blank=True, null=True, verbose_name='الوصف')),
                ('type', models.CharField(choices=[('image', 'صورة'), ('video', 'فيديو'), ('news', 'خبر')], default='image', max_length=10, verbose_name='نوع العنصر')),
                ('media_file', models.FileField(blank=True, null=True, upload_to='gallery_media/', verbose_name='ملف الوسائط')),
                ('media_url', models.URLField(blank=True, null=True, verbose_name='رابط خارجي للوسائط')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'عنصر معرض',
                'verbose_name_plural': 'معرض الصور والفيديوهات والأخبار',
                'ordering': ['-created_at'],
            },
        ),
    ]
