# Generated by Django 5.1.5 on 2025-11-08 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_galleryitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='galleryitem',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='news_covers/', verbose_name='صورة الغلاف'),
        ),
    ]
