# Generated by Django 5.1.5 on 2025-11-08 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_galleryitem_cover_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='galleryitem',
            name='cover_image_url',
            field=models.URLField(blank=True, null=True, verbose_name='رابط خارجي لصورة الغلاف'),
        ),
        migrations.AlterField(
            model_name='galleryitem',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='news_covers/', verbose_name='رفع صورة الغلاف'),
        ),
    ]
