# Generated by Django 5.1.5 on 2025-11-13 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_galleryitem_cover_image_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='galleryitem',
            name='seo_description',
            field=models.TextField(blank=True, null=True, verbose_name='وصف SEO'),
        ),
        migrations.AddField(
            model_name='galleryitem',
            name='seo_keywords',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='كلمات مفتاحية SEO (مفصولة بفواصل)'),
        ),
        migrations.AddField(
            model_name='galleryitem',
            name='seo_title',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='عنوان SEO'),
        ),
    ]
