# Generated by Django 5.1.5 on 2025-11-13 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_subscriber_alter_newslettersubscriber_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان الإشعار')),
                ('message', models.TextField(verbose_name='تفاصيل الإشعار')),
                ('is_active', models.BooleanField(default=True, verbose_name='مفعّل')),
                ('start_date', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('end_date', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الانتهاء')),
            ],
            options={
                'verbose_name': 'إشعار',
                'verbose_name_plural': 'الإشعارات',
            },
        ),
    ]
