# Generated by Django 5.1.5 on 2025-11-14 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_notification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitesettings',
            name='footer_text',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='hero_background',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='hero_background_url',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='hero_subtitle',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='hero_title',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='logo',
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='favicon',
            field=models.ImageField(blank=True, null=True, upload_to='favicon/'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='site_name',
            field=models.CharField(default='موقعي', max_length=200),
        ),
    ]
