# Generated by Django 5.1.5 on 2025-11-14 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_remove_sitesettings_footer_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='favicon_url',
            field=models.URLField(blank=True, help_text='ضع رابط Favicon إذا رغبت', max_length=500, null=True),
        ),
    ]
